# pyproject.toml
[build-system]
requires = ["setuptools>=61.0", "wheel", "ruamel.yaml"]
build-backend = "setuptools.build_meta"

[project]
name = "agentic_registry_agents_devops"
description = "AI Agent registry"
authors = [{name = "Vinod Kumar KP", email = "vinod.kunnum-purath@local.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
keywords = ["agent", "agent-server-registry"]
dynamic = ["scripts", "version"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

dependencies = [
    "oai-langgraph-core",
    "oai-agent-server",
    "mcp_registry_servers_development @ git+https://github.com/VinodKumarKP/ptr-development-mcp-servers.git@main",
    "mcp_registry_servers_cloud @ git+https://github.com/VinodKumarKP/ptr-cloud-mcp-servers.git@main",
    "mcp_registry_servers_enterprise @ git+https://github.com/VinodKumarKP/ptr-enterprise-mcp-servers.git@main",
    "langfuse"
]

[tool.uv.sources]
 oai-langgraph-core = { git = "https://github.com/VinodKumarKP/ptr_oai_adk.git", branch = "main", subdirectory = "packages/langgraph-core" }
 oai-agent-server = { git = "https://github.com/VinodKumarKP/ptr_oai_adk.git", branch = "main", subdirectory = "packages/agent-server" }


[project.urls]
Homepage = "https://github.com/local-Innersource/ptr_mcp_servers_registry"
Repository = "https://github.com/local-Innersource/ptr_mcp_servers_registry.gi"
Issues = "https://github.com/local-Innersource/ptr_mcp_servers_registry/issues"


[tool.setuptools.packages.find]
where = ["."]
include = ["agentic_registry_agents*"]
exclude = [".venv", "build", "agent_registry.egg_info"]

[tool.setuptools.package-data]
"agentic_registry_agents" = ["**/*"]

# Configuration for setuptools_scm (git-based versioning)
[tool.setuptools_scm]
write_to = "agentic_registry_agents/_version.py"
version_scheme = "post-release"
local_scheme = "no-local-version"

